### ISSUE TITLE
HTTPS for htsget demo link expired?

### ISSUE THREAD

**Issue by cmdcolin** [dnanexus-rnd/htsnexus#31]
Hi there

It would be great to demo access to an htsget endpoint like https://htsnexus.rnd.dnanex.us/v1/reads/1000genomes_low_coverage/NA20276?format=BAM however this produces an invalid https certificate (produces NET::ERR_CERT_DATE_INVALID by visiting this link on my computer?)

I know that is not specifically relevant to this repo but I was hoping maybe it would be tangentially related here :)

**Comment by mlin** [comment]
Hi, yea sorry this repo and the test server have been neglected as I've been working on some longer-term plumbing for it (this prototype partly motivated the compression and range query features in GenomicSQLite). I intend to get back to it but don't have a specific timeline right now. Please do ping me and/or ga4gh-htsget@ga4gh.org if we can help otherwise though

**Comment by cmdcolin** [comment]
Good to hear :) glad to hear progress on things like genomicsSQLite. I will just close for now
